### ISSUE TITLE
eliminate warning from iconv-loader

### ISSUE THREAD

**Issue by jspeis** [Datawheel/mondrian-rest-client#13]
If we can eliminate this warning that you get when you build with MRC in other projects, that would be great 😀 
```
    WARNING in /home/deploy/mobile/cnyvitals-site/node_modules/encoding/lib/iconv-loader.js
    9:12-34 Critical dependency: the request of a dependency is an expression
     @ /home/deploy/mobile/cnyvitals-site/node_modules/encoding/lib/iconv-loader.js
```

**Comment by frabarz** [comment]
I investigated this issue. The problem comes from the `encoding` package, from the chain `encoding` > `node-fetch` >  `isomorphic-fetch`. The way it makes a require call makes that warning.

The problem is, this problem is common, a lot of people is also getting it, but the maintainer hasn't done anything about it. 

There's not much we can do. The only think I can think of is replacing `isomorphic-fetch` with another library, like `axios`. I'll try some things and update this.

**Comment by davelandry** [comment]
👍 for switching to axios 😁
